### ISSUE TITLE
[Solicitud de documentación] Error ApacheLogging

### ISSUE THREAD

**Issue by alexlarraga1** [conekta/conekta-android#34]
Al momento de ejecutar la version 2.1

 ```log
 E  FATAL EXCEPTION: AsyncTask #2
    Process: mx.com.sfinx.jal.misaldo, PID: 4584
    java.lang.RuntimeException: An error occurred while executing doInBackground()
    	at android.os.AsyncTask$4.done(AsyncTask.java:415)
    	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
    	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    	at java.lang.Thread.run(Thread.java:1012)
    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/logging/LogFactory;
    	at org.apache.http.impl.client.AbstractHttpClient.<init>(AbstractHttpClient.java:182)
    	at org.apache.http.impl.client.DefaultHttpClient.<init>(DefaultHttpClient.java:150)
    	at io.conekta.conektasdk.Connection$Task.doInBackground(Connection.java:48)
    	at io.conekta.conektasdk.Connection$Task.doInBackground(Connection.java:43)
    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
    	at java.lang.Thread.run(Thread.java:1012) 
    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.LogFactory" on path: DexPathList
    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	at org.apache.http.impl.client.AbstractHttpClient.<init>(AbstractHttpClient.java:182) 
    	at org.apache.http.impl.client.DefaultHttpClient.<init>(DefaultHttpClient.java:150) 
    	at io.conekta.conektasdk.Connection$Task.doInBackground(Connection.java:48) 
    	at io.conekta.conektasdk.Connection$Task.doInBackground(Connection.java:43) 
    	at android.os.AsyncTask$3.call(AsyncTask.java:394) 
    	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
    	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
    	at java.lang.Thread.run(Thread.java:1012) 
```

La solución se encuentra al añadir en AndroidManifest.xml dentro la etiquieta <application>

```xml
    <uses-library android:name ="org.apache.http.legacy" android:required ="false"/>
```

**Comment by yargm** [comment]
Muchas gracias por compartir tu solución, me salvaste.
